name: NodeJs Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [ 16 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -f
    - run: npm run build
    - run: cp -r ./dist/* /home/dream4soft-salesapp/htdocs/salesapp.dream4soft.co.uk
