name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: DOTNET_CLI_HOME=/tmp dotnet restore "Salony.Wasm/Salony.Wasm.csproj"
    - name: Build
      run: DOTNET_CLI_HOME=/tmp dotnet build "Salony.Wasm/Salony.Wasm.csproj" --no-restore
    - name: Publish Project
      run: DOTNET_CLI_HOME=/tmp dotnet publish "Salony.Wasm/Salony.Wasm.csproj" -c Release  -o /home/ahmedkamal-salony/htdocs/salony.ahmedkamal.online
      
